### ISSUE TITLE
reigon locker plugin doesnt work with 117 HD

### ISSUE THREAD

**Issue by btl200** [slaytostay/region-locker#36] opened 2023-04-17 20:49 UTC
I know this is a minor issue but I want to be able to use the 117 HD graphics that are created using its own GPU and be able to use the region locker GPU to show where i can go and where i can't

**Comment by aHooder** [comment] 2023-04-17 21:19
This is a duplicate of #28, but it's a valid request. I'm not sure when I'll get around to it unfortunately, but I can add support for region locker's shader within 117 HD at some point.

**Closed by aHooder** 2023-04-17 21:19 UTC
